# vim: set sw=2 ts=2 sts=2 expandtab
---
- name: Asterisk SystemD Serices
  hosts: asterisk
  vars_files:
    - /etc/ansible/vars/asterisk.yml

  tasks:

    - name: "Load Vars"
      include_vars:
        file: "asterisk.yml"

    - name: "De-activate Normal Asterisk"
      systemd:
        state: stopped
        enabled: false
        name: asterisk



    - name: "De-Activate Asterisk instance"
      systemd:
        state: stopped
        enabled: false
        name: "asterisk-{{ item.id }}"
      loop: "{{ instance }}"

    - name: "Delete Asterisk instance"
      file:
        state: absent
        path: "/etc/systemd/system/asterisk-{{ item.id }}.service"
      loop: "{{ instance }}"

    - name: "reload Systemd instance"
      systemd:
        daemon_reload: true
